# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mrzap/progs/sQLux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mrzap/progs/sQLux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mrzap/progs/sQLux/CMakeFiles /home/mrzap/progs/sQLux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mrzap/progs/sQLux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SubmarineGitVersion

# Build rule for target.
SubmarineGitVersion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SubmarineGitVersion
.PHONY : SubmarineGitVersion

# fast build rule for target.
SubmarineGitVersion/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SubmarineGitVersion.dir/build.make CMakeFiles/SubmarineGitVersion.dir/build
.PHONY : SubmarineGitVersion/fast

#=============================================================================
# Target rules for targets named sqlux

# Build rule for target.
sqlux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sqlux
.PHONY : sqlux

# fast build rule for target.
sqlux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/build
.PHONY : sqlux/fast

Init.o: Init.c.o
.PHONY : Init.o

# target to build an object file
Init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/Init.c.o
.PHONY : Init.c.o

Init.i: Init.c.i
.PHONY : Init.i

# target to preprocess a source file
Init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/Init.c.i
.PHONY : Init.c.i

Init.s: Init.c.s
.PHONY : Init.s

# target to generate assembly for a file
Init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/Init.c.s
.PHONY : Init.c.s

QDisk.o: QDisk.c.o
.PHONY : QDisk.o

# target to build an object file
QDisk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QDisk.c.o
.PHONY : QDisk.c.o

QDisk.i: QDisk.c.i
.PHONY : QDisk.i

# target to preprocess a source file
QDisk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QDisk.c.i
.PHONY : QDisk.c.i

QDisk.s: QDisk.c.s
.PHONY : QDisk.s

# target to generate assembly for a file
QDisk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QDisk.c.s
.PHONY : QDisk.c.s

QL_basext.o: QL_basext.c.o
.PHONY : QL_basext.o

# target to build an object file
QL_basext.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_basext.c.o
.PHONY : QL_basext.c.o

QL_basext.i: QL_basext.c.i
.PHONY : QL_basext.i

# target to preprocess a source file
QL_basext.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_basext.c.i
.PHONY : QL_basext.c.i

QL_basext.s: QL_basext.c.s
.PHONY : QL_basext.s

# target to generate assembly for a file
QL_basext.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_basext.c.s
.PHONY : QL_basext.c.s

QL_boot.o: QL_boot.c.o
.PHONY : QL_boot.o

# target to build an object file
QL_boot.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_boot.c.o
.PHONY : QL_boot.c.o

QL_boot.i: QL_boot.c.i
.PHONY : QL_boot.i

# target to preprocess a source file
QL_boot.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_boot.c.i
.PHONY : QL_boot.c.i

QL_boot.s: QL_boot.c.s
.PHONY : QL_boot.s

# target to generate assembly for a file
QL_boot.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_boot.c.s
.PHONY : QL_boot.c.s

QL_cconv.o: QL_cconv.c.o
.PHONY : QL_cconv.o

# target to build an object file
QL_cconv.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_cconv.c.o
.PHONY : QL_cconv.c.o

QL_cconv.i: QL_cconv.c.i
.PHONY : QL_cconv.i

# target to preprocess a source file
QL_cconv.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_cconv.c.i
.PHONY : QL_cconv.c.i

QL_cconv.s: QL_cconv.c.s
.PHONY : QL_cconv.s

# target to generate assembly for a file
QL_cconv.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_cconv.c.s
.PHONY : QL_cconv.c.s

QL_config.o: QL_config.c.o
.PHONY : QL_config.o

# target to build an object file
QL_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_config.c.o
.PHONY : QL_config.c.o

QL_config.i: QL_config.c.i
.PHONY : QL_config.i

# target to preprocess a source file
QL_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_config.c.i
.PHONY : QL_config.c.i

QL_config.s: QL_config.c.s
.PHONY : QL_config.s

# target to generate assembly for a file
QL_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_config.c.s
.PHONY : QL_config.c.s

QL_driver.o: QL_driver.c.o
.PHONY : QL_driver.o

# target to build an object file
QL_driver.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_driver.c.o
.PHONY : QL_driver.c.o

QL_driver.i: QL_driver.c.i
.PHONY : QL_driver.i

# target to preprocess a source file
QL_driver.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_driver.c.i
.PHONY : QL_driver.c.i

QL_driver.s: QL_driver.c.s
.PHONY : QL_driver.s

# target to generate assembly for a file
QL_driver.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_driver.c.s
.PHONY : QL_driver.c.s

QL_files.o: QL_files.c.o
.PHONY : QL_files.o

# target to build an object file
QL_files.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_files.c.o
.PHONY : QL_files.c.o

QL_files.i: QL_files.c.i
.PHONY : QL_files.i

# target to preprocess a source file
QL_files.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_files.c.i
.PHONY : QL_files.c.i

QL_files.s: QL_files.c.s
.PHONY : QL_files.s

# target to generate assembly for a file
QL_files.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_files.c.s
.PHONY : QL_files.c.s

QL_hardware.o: QL_hardware.c.o
.PHONY : QL_hardware.o

# target to build an object file
QL_hardware.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_hardware.c.o
.PHONY : QL_hardware.c.o

QL_hardware.i: QL_hardware.c.i
.PHONY : QL_hardware.i

# target to preprocess a source file
QL_hardware.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_hardware.c.i
.PHONY : QL_hardware.c.i

QL_hardware.s: QL_hardware.c.s
.PHONY : QL_hardware.s

# target to generate assembly for a file
QL_hardware.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_hardware.c.s
.PHONY : QL_hardware.c.s

QL_poll.o: QL_poll.c.o
.PHONY : QL_poll.o

# target to build an object file
QL_poll.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_poll.c.o
.PHONY : QL_poll.c.o

QL_poll.i: QL_poll.c.i
.PHONY : QL_poll.i

# target to preprocess a source file
QL_poll.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_poll.c.i
.PHONY : QL_poll.c.i

QL_poll.s: QL_poll.c.s
.PHONY : QL_poll.s

# target to generate assembly for a file
QL_poll.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_poll.c.s
.PHONY : QL_poll.c.s

QL_screen.o: QL_screen.c.o
.PHONY : QL_screen.o

# target to build an object file
QL_screen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_screen.c.o
.PHONY : QL_screen.c.o

QL_screen.i: QL_screen.c.i
.PHONY : QL_screen.i

# target to preprocess a source file
QL_screen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_screen.c.i
.PHONY : QL_screen.c.i

QL_screen.s: QL_screen.c.s
.PHONY : QL_screen.s

# target to generate assembly for a file
QL_screen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_screen.c.s
.PHONY : QL_screen.c.s

QL_serial.o: QL_serial.c.o
.PHONY : QL_serial.o

# target to build an object file
QL_serial.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_serial.c.o
.PHONY : QL_serial.c.o

QL_serial.i: QL_serial.c.i
.PHONY : QL_serial.i

# target to preprocess a source file
QL_serial.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_serial.c.i
.PHONY : QL_serial.c.i

QL_serial.s: QL_serial.c.s
.PHONY : QL_serial.s

# target to generate assembly for a file
QL_serial.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_serial.c.s
.PHONY : QL_serial.c.s

QL_sound.o: QL_sound.c.o
.PHONY : QL_sound.o

# target to build an object file
QL_sound.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_sound.c.o
.PHONY : QL_sound.c.o

QL_sound.i: QL_sound.c.i
.PHONY : QL_sound.i

# target to preprocess a source file
QL_sound.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_sound.c.i
.PHONY : QL_sound.c.i

QL_sound.s: QL_sound.c.s
.PHONY : QL_sound.s

# target to generate assembly for a file
QL_sound.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QL_sound.c.s
.PHONY : QL_sound.c.s

QLip.o: QLip.c.o
.PHONY : QLip.o

# target to build an object file
QLip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QLip.c.o
.PHONY : QLip.c.o

QLip.i: QLip.c.i
.PHONY : QLip.i

# target to preprocess a source file
QLip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QLip.c.i
.PHONY : QLip.c.i

QLip.s: QLip.c.s
.PHONY : QLip.s

# target to generate assembly for a file
QLip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QLip.c.s
.PHONY : QLip.c.s

QLserio.o: QLserio.c.o
.PHONY : QLserio.o

# target to build an object file
QLserio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QLserio.c.o
.PHONY : QLserio.c.o

QLserio.i: QLserio.c.i
.PHONY : QLserio.i

# target to preprocess a source file
QLserio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QLserio.c.i
.PHONY : QLserio.c.i

QLserio.s: QLserio.c.s
.PHONY : QLserio.s

# target to generate assembly for a file
QLserio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QLserio.c.s
.PHONY : QLserio.c.s

QLtraps.o: QLtraps.c.o
.PHONY : QLtraps.o

# target to build an object file
QLtraps.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QLtraps.c.o
.PHONY : QLtraps.c.o

QLtraps.i: QLtraps.c.i
.PHONY : QLtraps.i

# target to preprocess a source file
QLtraps.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QLtraps.c.i
.PHONY : QLtraps.c.i

QLtraps.s: QLtraps.c.s
.PHONY : QLtraps.s

# target to generate assembly for a file
QLtraps.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QLtraps.c.s
.PHONY : QLtraps.c.s

QVFS.o: QVFS.c.o
.PHONY : QVFS.o

# target to build an object file
QVFS.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QVFS.c.o
.PHONY : QVFS.c.o

QVFS.i: QVFS.c.i
.PHONY : QVFS.i

# target to preprocess a source file
QVFS.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QVFS.c.i
.PHONY : QVFS.c.i

QVFS.s: QVFS.c.s
.PHONY : QVFS.s

# target to generate assembly for a file
QVFS.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/QVFS.c.s
.PHONY : QVFS.c.s

Xscreen.o: Xscreen.c.o
.PHONY : Xscreen.o

# target to build an object file
Xscreen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/Xscreen.c.o
.PHONY : Xscreen.c.o

Xscreen.i: Xscreen.c.i
.PHONY : Xscreen.i

# target to preprocess a source file
Xscreen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/Xscreen.c.i
.PHONY : Xscreen.c.i

Xscreen.s: Xscreen.c.s
.PHONY : Xscreen.s

# target to generate assembly for a file
Xscreen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/Xscreen.c.s
.PHONY : Xscreen.c.s

args/src/args.o: args/src/args.c.o
.PHONY : args/src/args.o

# target to build an object file
args/src/args.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/args/src/args.c.o
.PHONY : args/src/args.c.o

args/src/args.i: args/src/args.c.i
.PHONY : args/src/args.i

# target to preprocess a source file
args/src/args.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/args/src/args.c.i
.PHONY : args/src/args.c.i

args/src/args.s: args/src/args.c.s
.PHONY : args/src/args.s

# target to generate assembly for a file
args/src/args.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/args/src/args.c.s
.PHONY : args/src/args.c.s

dummies.o: dummies.c.o
.PHONY : dummies.o

# target to build an object file
dummies.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/dummies.c.o
.PHONY : dummies.c.o

dummies.i: dummies.c.i
.PHONY : dummies.i

# target to preprocess a source file
dummies.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/dummies.c.i
.PHONY : dummies.c.i

dummies.s: dummies.c.s
.PHONY : dummies.s

# target to generate assembly for a file
dummies.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/dummies.c.s
.PHONY : dummies.c.s

general.o: general.c.o
.PHONY : general.o

# target to build an object file
general.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/general.c.o
.PHONY : general.c.o

general.i: general.c.i
.PHONY : general.i

# target to preprocess a source file
general.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/general.c.i
.PHONY : general.c.i

general.s: general.c.s
.PHONY : general.s

# target to generate assembly for a file
general.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/general.c.s
.PHONY : general.c.s

iexl_general.o: iexl_general.c.o
.PHONY : iexl_general.o

# target to build an object file
iexl_general.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/iexl_general.c.o
.PHONY : iexl_general.c.o

iexl_general.i: iexl_general.c.i
.PHONY : iexl_general.i

# target to preprocess a source file
iexl_general.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/iexl_general.c.i
.PHONY : iexl_general.c.i

iexl_general.s: iexl_general.c.s
.PHONY : iexl_general.s

# target to generate assembly for a file
iexl_general.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/iexl_general.c.s
.PHONY : iexl_general.c.s

inih/ini.o: inih/ini.c.o
.PHONY : inih/ini.o

# target to build an object file
inih/ini.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/inih/ini.c.o
.PHONY : inih/ini.c.o

inih/ini.i: inih/ini.c.i
.PHONY : inih/ini.i

# target to preprocess a source file
inih/ini.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/inih/ini.c.i
.PHONY : inih/ini.c.i

inih/ini.s: inih/ini.c.s
.PHONY : inih/ini.s

# target to generate assembly for a file
inih/ini.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/inih/ini.c.s
.PHONY : inih/ini.c.s

instructions_ao.o: instructions_ao.c.o
.PHONY : instructions_ao.o

# target to build an object file
instructions_ao.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/instructions_ao.c.o
.PHONY : instructions_ao.c.o

instructions_ao.i: instructions_ao.c.i
.PHONY : instructions_ao.i

# target to preprocess a source file
instructions_ao.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/instructions_ao.c.i
.PHONY : instructions_ao.c.i

instructions_ao.s: instructions_ao.c.s
.PHONY : instructions_ao.s

# target to generate assembly for a file
instructions_ao.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/instructions_ao.c.s
.PHONY : instructions_ao.c.s

instructions_pz.o: instructions_pz.c.o
.PHONY : instructions_pz.o

# target to build an object file
instructions_pz.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/instructions_pz.c.o
.PHONY : instructions_pz.c.o

instructions_pz.i: instructions_pz.c.i
.PHONY : instructions_pz.i

# target to preprocess a source file
instructions_pz.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/instructions_pz.c.i
.PHONY : instructions_pz.c.i

instructions_pz.s: instructions_pz.c.s
.PHONY : instructions_pz.s

# target to generate assembly for a file
instructions_pz.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/instructions_pz.c.s
.PHONY : instructions_pz.c.s

memaccess.o: memaccess.c.o
.PHONY : memaccess.o

# target to build an object file
memaccess.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/memaccess.c.o
.PHONY : memaccess.c.o

memaccess.i: memaccess.c.i
.PHONY : memaccess.i

# target to preprocess a source file
memaccess.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/memaccess.c.i
.PHONY : memaccess.c.i

memaccess.s: memaccess.c.s
.PHONY : memaccess.s

# target to generate assembly for a file
memaccess.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/memaccess.c.s
.PHONY : memaccess.c.s

mmodes.o: mmodes.c.o
.PHONY : mmodes.o

# target to build an object file
mmodes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/mmodes.c.o
.PHONY : mmodes.c.o

mmodes.i: mmodes.c.i
.PHONY : mmodes.i

# target to preprocess a source file
mmodes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/mmodes.c.i
.PHONY : mmodes.c.i

mmodes.s: mmodes.c.s
.PHONY : mmodes.s

# target to generate assembly for a file
mmodes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/mmodes.c.s
.PHONY : mmodes.c.s

pty.o: pty.c.o
.PHONY : pty.o

# target to build an object file
pty.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/pty.c.o
.PHONY : pty.c.o

pty.i: pty.c.i
.PHONY : pty.i

# target to preprocess a source file
pty.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/pty.c.i
.PHONY : pty.c.i

pty.s: pty.c.s
.PHONY : pty.s

# target to generate assembly for a file
pty.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/pty.c.s
.PHONY : pty.c.s

qmtrap.o: qmtrap.c.o
.PHONY : qmtrap.o

# target to build an object file
qmtrap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/qmtrap.c.o
.PHONY : qmtrap.c.o

qmtrap.i: qmtrap.c.i
.PHONY : qmtrap.i

# target to preprocess a source file
qmtrap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/qmtrap.c.i
.PHONY : qmtrap.c.i

qmtrap.s: qmtrap.c.s
.PHONY : qmtrap.s

# target to generate assembly for a file
qmtrap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/qmtrap.c.s
.PHONY : qmtrap.c.s

sds/sds.o: sds/sds.c.o
.PHONY : sds/sds.o

# target to build an object file
sds/sds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/sds/sds.c.o
.PHONY : sds/sds.c.o

sds/sds.i: sds/sds.c.i
.PHONY : sds/sds.i

# target to preprocess a source file
sds/sds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/sds/sds.c.i
.PHONY : sds/sds.c.i

sds/sds.s: sds/sds.c.s
.PHONY : sds/sds.s

# target to generate assembly for a file
sds/sds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/sds/sds.c.s
.PHONY : sds/sds.c.s

sqlux_bdi.o: sqlux_bdi.c.o
.PHONY : sqlux_bdi.o

# target to build an object file
sqlux_bdi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/sqlux_bdi.c.o
.PHONY : sqlux_bdi.c.o

sqlux_bdi.i: sqlux_bdi.c.i
.PHONY : sqlux_bdi.i

# target to preprocess a source file
sqlux_bdi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/sqlux_bdi.c.i
.PHONY : sqlux_bdi.c.i

sqlux_bdi.s: sqlux_bdi.c.s
.PHONY : sqlux_bdi.s

# target to generate assembly for a file
sqlux_bdi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/sqlux_bdi.c.s
.PHONY : sqlux_bdi.c.s

src/GPUshaders.o: src/GPUshaders.c.o
.PHONY : src/GPUshaders.o

# target to build an object file
src/GPUshaders.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/GPUshaders.c.o
.PHONY : src/GPUshaders.c.o

src/GPUshaders.i: src/GPUshaders.c.i
.PHONY : src/GPUshaders.i

# target to preprocess a source file
src/GPUshaders.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/GPUshaders.c.i
.PHONY : src/GPUshaders.c.i

src/GPUshaders.s: src/GPUshaders.c.s
.PHONY : src/GPUshaders.s

# target to generate assembly for a file
src/GPUshaders.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/GPUshaders.c.s
.PHONY : src/GPUshaders.c.s

src/SDL2main.o: src/SDL2main.c.o
.PHONY : src/SDL2main.o

# target to build an object file
src/SDL2main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/SDL2main.c.o
.PHONY : src/SDL2main.c.o

src/SDL2main.i: src/SDL2main.c.i
.PHONY : src/SDL2main.i

# target to preprocess a source file
src/SDL2main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/SDL2main.c.i
.PHONY : src/SDL2main.c.i

src/SDL2main.s: src/SDL2main.c.s
.PHONY : src/SDL2main.s

# target to generate assembly for a file
src/SDL2main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/SDL2main.c.s
.PHONY : src/SDL2main.c.s

src/SDL2screen.o: src/SDL2screen.c.o
.PHONY : src/SDL2screen.o

# target to build an object file
src/SDL2screen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/SDL2screen.c.o
.PHONY : src/SDL2screen.c.o

src/SDL2screen.i: src/SDL2screen.c.i
.PHONY : src/SDL2screen.i

# target to preprocess a source file
src/SDL2screen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/SDL2screen.c.i
.PHONY : src/SDL2screen.c.i

src/SDL2screen.s: src/SDL2screen.c.s
.PHONY : src/SDL2screen.s

# target to generate assembly for a file
src/SDL2screen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/SDL2screen.c.s
.PHONY : src/SDL2screen.c.s

src/emulator_init.o: src/emulator_init.c.o
.PHONY : src/emulator_init.o

# target to build an object file
src/emulator_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/emulator_init.c.o
.PHONY : src/emulator_init.c.o

src/emulator_init.i: src/emulator_init.c.i
.PHONY : src/emulator_init.i

# target to preprocess a source file
src/emulator_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/emulator_init.c.i
.PHONY : src/emulator_init.c.i

src/emulator_init.s: src/emulator_init.c.s
.PHONY : src/emulator_init.s

# target to generate assembly for a file
src/emulator_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/emulator_init.c.s
.PHONY : src/emulator_init.c.s

src/emulator_options.o: src/emulator_options.c.o
.PHONY : src/emulator_options.o

# target to build an object file
src/emulator_options.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/emulator_options.c.o
.PHONY : src/emulator_options.c.o

src/emulator_options.i: src/emulator_options.c.i
.PHONY : src/emulator_options.i

# target to preprocess a source file
src/emulator_options.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/emulator_options.c.i
.PHONY : src/emulator_options.c.i

src/emulator_options.s: src/emulator_options.c.s
.PHONY : src/emulator_options.s

# target to generate assembly for a file
src/emulator_options.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/emulator_options.c.s
.PHONY : src/emulator_options.c.s

src/sqlux_hexdump.o: src/sqlux_hexdump.c.o
.PHONY : src/sqlux_hexdump.o

# target to build an object file
src/sqlux_hexdump.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/sqlux_hexdump.c.o
.PHONY : src/sqlux_hexdump.c.o

src/sqlux_hexdump.i: src/sqlux_hexdump.c.i
.PHONY : src/sqlux_hexdump.i

# target to preprocess a source file
src/sqlux_hexdump.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/sqlux_hexdump.c.i
.PHONY : src/sqlux_hexdump.c.i

src/sqlux_hexdump.s: src/sqlux_hexdump.c.s
.PHONY : src/sqlux_hexdump.s

# target to generate assembly for a file
src/sqlux_hexdump.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/sqlux_hexdump.c.s
.PHONY : src/sqlux_hexdump.c.s

src/sqlux_windows.o: src/sqlux_windows.c.o
.PHONY : src/sqlux_windows.o

# target to build an object file
src/sqlux_windows.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/sqlux_windows.c.o
.PHONY : src/sqlux_windows.c.o

src/sqlux_windows.i: src/sqlux_windows.c.i
.PHONY : src/sqlux_windows.i

# target to preprocess a source file
src/sqlux_windows.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/sqlux_windows.c.i
.PHONY : src/sqlux_windows.c.i

src/sqlux_windows.s: src/sqlux_windows.c.s
.PHONY : src/sqlux_windows.s

# target to generate assembly for a file
src/sqlux_windows.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/src/sqlux_windows.c.s
.PHONY : src/sqlux_windows.c.s

trace.o: trace.c.o
.PHONY : trace.o

# target to build an object file
trace.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/trace.c.o
.PHONY : trace.c.o

trace.i: trace.c.i
.PHONY : trace.i

# target to preprocess a source file
trace.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/trace.c.i
.PHONY : trace.c.i

trace.s: trace.c.s
.PHONY : trace.s

# target to generate assembly for a file
trace.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/trace.c.s
.PHONY : trace.c.s

unixstuff.o: unixstuff.c.o
.PHONY : unixstuff.o

# target to build an object file
unixstuff.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/unixstuff.c.o
.PHONY : unixstuff.c.o

unixstuff.i: unixstuff.c.i
.PHONY : unixstuff.i

# target to preprocess a source file
unixstuff.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/unixstuff.c.i
.PHONY : unixstuff.c.i

unixstuff.s: unixstuff.c.s
.PHONY : unixstuff.s

# target to generate assembly for a file
unixstuff.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/unixstuff.c.s
.PHONY : unixstuff.c.s

util.o: util.c.o
.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/util.c.s
.PHONY : util.c.s

uxfile.o: uxfile.c.o
.PHONY : uxfile.o

# target to build an object file
uxfile.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/uxfile.c.o
.PHONY : uxfile.c.o

uxfile.i: uxfile.c.i
.PHONY : uxfile.i

# target to preprocess a source file
uxfile.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/uxfile.c.i
.PHONY : uxfile.c.i

uxfile.s: uxfile.c.s
.PHONY : uxfile.s

# target to generate assembly for a file
uxfile.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/uxfile.c.s
.PHONY : uxfile.c.s

version.o: version.c.o
.PHONY : version.o

# target to build an object file
version.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/version.c.o
.PHONY : version.c.o

version.i: version.c.i
.PHONY : version.i

# target to preprocess a source file
version.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/version.c.i
.PHONY : version.c.i

version.s: version.c.s
.PHONY : version.s

# target to generate assembly for a file
version.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/version.c.s
.PHONY : version.c.s

xc68.o: xc68.c.o
.PHONY : xc68.o

# target to build an object file
xc68.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/xc68.c.o
.PHONY : xc68.c.o

xc68.i: xc68.c.i
.PHONY : xc68.i

# target to preprocess a source file
xc68.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/xc68.c.i
.PHONY : xc68.c.i

xc68.s: xc68.c.s
.PHONY : xc68.s

# target to generate assembly for a file
xc68.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/xc68.c.s
.PHONY : xc68.c.s

xcodes.o: xcodes.c.o
.PHONY : xcodes.o

# target to build an object file
xcodes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/xcodes.c.o
.PHONY : xcodes.c.o

xcodes.i: xcodes.c.i
.PHONY : xcodes.i

# target to preprocess a source file
xcodes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/xcodes.c.i
.PHONY : xcodes.c.i

xcodes.s: xcodes.c.s
.PHONY : xcodes.s

# target to generate assembly for a file
xcodes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/xcodes.c.s
.PHONY : xcodes.c.s

xqlmouse.o: xqlmouse.c.o
.PHONY : xqlmouse.o

# target to build an object file
xqlmouse.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/xqlmouse.c.o
.PHONY : xqlmouse.c.o

xqlmouse.i: xqlmouse.c.i
.PHONY : xqlmouse.i

# target to preprocess a source file
xqlmouse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/xqlmouse.c.i
.PHONY : xqlmouse.c.i

xqlmouse.s: xqlmouse.c.s
.PHONY : xqlmouse.s

# target to generate assembly for a file
xqlmouse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sqlux.dir/build.make CMakeFiles/sqlux.dir/xqlmouse.c.s
.PHONY : xqlmouse.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SubmarineGitVersion"
	@echo "... sqlux"
	@echo "... Init.o"
	@echo "... Init.i"
	@echo "... Init.s"
	@echo "... QDisk.o"
	@echo "... QDisk.i"
	@echo "... QDisk.s"
	@echo "... QL_basext.o"
	@echo "... QL_basext.i"
	@echo "... QL_basext.s"
	@echo "... QL_boot.o"
	@echo "... QL_boot.i"
	@echo "... QL_boot.s"
	@echo "... QL_cconv.o"
	@echo "... QL_cconv.i"
	@echo "... QL_cconv.s"
	@echo "... QL_config.o"
	@echo "... QL_config.i"
	@echo "... QL_config.s"
	@echo "... QL_driver.o"
	@echo "... QL_driver.i"
	@echo "... QL_driver.s"
	@echo "... QL_files.o"
	@echo "... QL_files.i"
	@echo "... QL_files.s"
	@echo "... QL_hardware.o"
	@echo "... QL_hardware.i"
	@echo "... QL_hardware.s"
	@echo "... QL_poll.o"
	@echo "... QL_poll.i"
	@echo "... QL_poll.s"
	@echo "... QL_screen.o"
	@echo "... QL_screen.i"
	@echo "... QL_screen.s"
	@echo "... QL_serial.o"
	@echo "... QL_serial.i"
	@echo "... QL_serial.s"
	@echo "... QL_sound.o"
	@echo "... QL_sound.i"
	@echo "... QL_sound.s"
	@echo "... QLip.o"
	@echo "... QLip.i"
	@echo "... QLip.s"
	@echo "... QLserio.o"
	@echo "... QLserio.i"
	@echo "... QLserio.s"
	@echo "... QLtraps.o"
	@echo "... QLtraps.i"
	@echo "... QLtraps.s"
	@echo "... QVFS.o"
	@echo "... QVFS.i"
	@echo "... QVFS.s"
	@echo "... Xscreen.o"
	@echo "... Xscreen.i"
	@echo "... Xscreen.s"
	@echo "... args/src/args.o"
	@echo "... args/src/args.i"
	@echo "... args/src/args.s"
	@echo "... dummies.o"
	@echo "... dummies.i"
	@echo "... dummies.s"
	@echo "... general.o"
	@echo "... general.i"
	@echo "... general.s"
	@echo "... iexl_general.o"
	@echo "... iexl_general.i"
	@echo "... iexl_general.s"
	@echo "... inih/ini.o"
	@echo "... inih/ini.i"
	@echo "... inih/ini.s"
	@echo "... instructions_ao.o"
	@echo "... instructions_ao.i"
	@echo "... instructions_ao.s"
	@echo "... instructions_pz.o"
	@echo "... instructions_pz.i"
	@echo "... instructions_pz.s"
	@echo "... memaccess.o"
	@echo "... memaccess.i"
	@echo "... memaccess.s"
	@echo "... mmodes.o"
	@echo "... mmodes.i"
	@echo "... mmodes.s"
	@echo "... pty.o"
	@echo "... pty.i"
	@echo "... pty.s"
	@echo "... qmtrap.o"
	@echo "... qmtrap.i"
	@echo "... qmtrap.s"
	@echo "... sds/sds.o"
	@echo "... sds/sds.i"
	@echo "... sds/sds.s"
	@echo "... sqlux_bdi.o"
	@echo "... sqlux_bdi.i"
	@echo "... sqlux_bdi.s"
	@echo "... src/GPUshaders.o"
	@echo "... src/GPUshaders.i"
	@echo "... src/GPUshaders.s"
	@echo "... src/SDL2main.o"
	@echo "... src/SDL2main.i"
	@echo "... src/SDL2main.s"
	@echo "... src/SDL2screen.o"
	@echo "... src/SDL2screen.i"
	@echo "... src/SDL2screen.s"
	@echo "... src/emulator_init.o"
	@echo "... src/emulator_init.i"
	@echo "... src/emulator_init.s"
	@echo "... src/emulator_options.o"
	@echo "... src/emulator_options.i"
	@echo "... src/emulator_options.s"
	@echo "... src/sqlux_hexdump.o"
	@echo "... src/sqlux_hexdump.i"
	@echo "... src/sqlux_hexdump.s"
	@echo "... src/sqlux_windows.o"
	@echo "... src/sqlux_windows.i"
	@echo "... src/sqlux_windows.s"
	@echo "... trace.o"
	@echo "... trace.i"
	@echo "... trace.s"
	@echo "... unixstuff.o"
	@echo "... unixstuff.i"
	@echo "... unixstuff.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... uxfile.o"
	@echo "... uxfile.i"
	@echo "... uxfile.s"
	@echo "... version.o"
	@echo "... version.i"
	@echo "... version.s"
	@echo "... xc68.o"
	@echo "... xc68.i"
	@echo "... xc68.s"
	@echo "... xcodes.o"
	@echo "... xcodes.i"
	@echo "... xcodes.s"
	@echo "... xqlmouse.o"
	@echo "... xqlmouse.i"
	@echo "... xqlmouse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

