name: Build and Upload Tagged Release

on:
  push:
    tags:
      - "**"
    branches:
      - master
  pull_request:

env:
  GIT_PAGER:

jobs:
  get_release_name:
    name: Get Release Name
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          filter: "blob:none"
          fetch-tags: "false"
          fetch-depth: "1000"
          submodules: "true"
      - name: Define Release Name
        id: DefineName
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            echo "RELEASE_NAME=$GITHUB_REFNAME" >> "$GITHUB_OUTPUT"
          elif [[ "$GITHUB_REF_NAME" == "master" ]]; then
            echo "RELEASE_NAME=latest" >> "$GITHUB_OUTPUT"
            git tag -f latest
            git push origin -f latest
          else
            echo "RELEASE_NAME=latest" >> "$GITHUB_OUTPUT"
          fi
    outputs:
      RELEASE_NAME: ${{ steps.DefineName.outputs.RELEASE_NAME }}

  #### Prepare buildable source
  zip_source:
    name: Zip Complete Source
    runs-on: ubuntu-24.04
    needs:
      - get_release_name
    env:
      RELEASE_NAME: ${{ needs.get_release_name.outputs.RELEASE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          filter: "blob:none"
          fetch-tags: "false"
          fetch-depth: "1000"
          submodules: "true"
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip
      - name: Zip The Source
        run: |
          zip -r sqlux-source-${{ env.RELEASE_NAME }}.zip ./*
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          retention-days: 1
          name: sqlux-source-${{ env.RELEASE_NAME }}
          path: sqlux-source-${{ env.RELEASE_NAME }}.zip

  #### Build Manual PDF
  build_manual:
    name: Build sQLux Manual
    runs-on: ubuntu-24.04
    needs:
      - get_release_name
    env:
      RELEASE_NAME: ${{needs.get_release_name.outputs.RELEASE_NAME}}
    steps:
      - uses: actions/checkout@v6
        with:
          filter: "blob:none"
          fetch-tags: "false"
          fetch-depth: "1000"
          submodules: "true"
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y pandoc wkhtmltopdf
      - name: Generate Manual
        run: |
          pandoc -f markdown -t html5 --metadata title="sQLux Manual" docs/sqlux.md -o sqlux-${{ env.RELEASE_NAME }}.pdf
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          retention-days: 1
          name: sqlux-${{ env.RELEASE_NAME }}
          path: sqlux-${{ env.RELEASE_NAME }}.pdf

  #### Linux x86_64
  build:
    strategy:
      matrix:
        include:
          - {
              os: ubuntu,
              image: ubuntu-24.04,
              pkg: apt,
              arch: x86_64,
              shell: bash,
            }
          - {
              os: ubuntu,
              image: ubuntu-24.04-arm,
              pkg: apt,
              arch: aarch64,
              shell: bash,
            }
          - {
              os: macos,
              image: macos-15,
              pkg: brew,
              arch: aarch64,
              shell: bash,
            }
          - {
              os: mingw32,
              image: windows-2022,
              pkg: mingw,
              arch: i686,
              shell: "msys2 {0}",
            }
          - {
              os: mingw64,
              image: windows-2022,
              pkg: mingw,
              arch: x86_64,
              shell: "msys2 {0}",
            }
    defaults:
      run:
        shell: ${{ matrix.shell }}
    name: Build ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.image }}
    needs:
      - get_release_name
    env:
      RELEASE_NAME: ${{needs.get_release_name.outputs.RELEASE_NAME}}
    steps:
      - uses: actions/checkout@v6
        with:
          filter: "blob:none"
          fetch-tags: "false"
          fetch-depth: "1000"
          submodules: "true"
      - name: Install Dependencies - apt
        if: ${{ matrix.pkg == 'apt' }}
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            git \
            libglu1-mesa-dev \
            libsdl2-dev
      - name: Install Dependencies - msys2
        uses: msys2/setup-msys2@v2
        if: ${{ matrix.pkg == 'mingw' }}
        with:
          msystem: ${{ matrix.os }}
          update: true
          install: >-
            git
            zip
            mingw-w64-${{matrix.arch}}-cc
            mingw-w64-${{matrix.arch}}-SDL2
            mingw-w64-${{matrix.arch}}-cmake
      - name: Install Dependencies - brew
        if: ${{ matrix.pkg == 'brew' }}
        run: |
          brew install sdl2
      - name: Configure with cmake
        run: |
          cmake -B build/ -DCMAKE_BUILD_TYPE=Release -DSUPPORT_SHADERS=True
      - name: Build with cmake
        run: |
          cmake --build build/ --parallel 4
      - name: Create Artifact
        run: |
          mkdir  sqlux-${{ matrix.arch }}-${{ matrix.os }}-${{ env.RELEASE_NAME }}/
          cp -v  examples/sqlux.ini     sqlux-${{ matrix.arch }}-${{ matrix.os }}-${{ env.RELEASE_NAME }}/
          cp -vr examples/mdv*          sqlux-${{ matrix.arch }}-${{ matrix.os }}-${{ env.RELEASE_NAME }}/
          cp -vr roms                   sqlux-${{ matrix.arch }}-${{ matrix.os }}-${{ env.RELEASE_NAME }}/
          cp -v  build/sqlux            sqlux-${{ matrix.arch }}-${{ matrix.os }}-${{ env.RELEASE_NAME }}/
          zip -r sqlux-${{ matrix.arch }}-${{ matrix.os }}-${{ env.RELEASE_NAME }}.zip \
                 sqlux-${{ matrix.arch }}-${{ matrix.os }}-${{ env.RELEASE_NAME }}/
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          retention-days: 1
          name: sqlux-${{ matrix.arch }}-${{ matrix.os }}-${{ env.RELEASE_NAME }}
          path: sqlux-${{ matrix.arch }}-${{ matrix.os }}-${{ env.RELEASE_NAME }}.zip

  #### Upload artifacts to Releases
  upload_artifacts:
    name: Upload Artifacts to Releases
    runs-on: ubuntu-24.04
    needs:
      - get_release_name
      - build
      - build_manual
      - zip_source
    env:
      RELEASE_NAME: ${{ needs.get_release_name.outputs.RELEASE_NAME }}
    steps:
      - name: Restore Artifacts Cache
        uses: actions/download-artifact@v8
        with:
          path: artifacts
      - name: list Artifacts
        run: |
          ls -la artifacts/*/*
      - name: Release ${{ env.RELEASE_NAME }}
        uses: softprops/action-gh-release@v2
        if: ${{ (github.ref_type == 'tag') || (github.ref_name == 'master') }}
        with:
          make_latest: true
          generate_release_notes: true
          append_body: false
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.RELEASE_NAME }}
          files: |
            artifacts/*/*.zip
            artifacts/*/*.pdf
